Reuse the badge component in avatar
sl-design-system/components pull request #1325
Opened 2024-06-11 07:49 UTC by jpzwarte

2024-06-12 12:51 UTC, anna-lach approved these changes

2024-06-12 12:51 UTC, anna-lach commented on packages/components/avatar/src/avatar.ts
> -  @property({ reflect: true }) status?: UserStatus;
Can you please change examples on the website as well? There are few with `status` left :)

<img width="949" alt="image" src="https://github.com/sl-design-system/components/assets/111562742/123ce316-b308-4565-aec2-7cf3ebd43086">

2024-06-12 12:51 UTC, anna-lach commented on packages/components/avatar/src/avatar.scss
> +:host([size='lg']) {
What about using `@each` for sizes like in the buttons?

2024-06-12 13:35 UTC, Diaan requested changes

2024-06-12 13:35 UTC, Diaan commented on packages/components/avatar/src/avatar.ts
>              <sl-tooltip id="avatar-tooltip">${this.displayName}</sl-tooltip>
This doesn't work anymore

2024-06-12 13:49 UTC, Diaan commented
Not sure this is how it is supposed to look? 
<img width="927" alt="image" src="https://github.com/sl-design-system/components/assets/1351956/f67c79be-55d2-4c94-92f3-746e1cea4982">
Wrong icon and wrong icon size

2024-06-12 14:04 UTC, Diaan commented on packages/components/avatar/src/avatar.ts
> + * @slot fallback - The fallback content to display when no picture is set.
Why would you want this as a slot? You want this to be the same over your entire application (with a possible overwrite, but not sure why you would want that.) so I would suggest an `sl-icon` which we choose.

2024-06-12 14:15 UTC, Diaan commented on packages/components/avatar/src/avatar.ts
> + * @slot fallback - The fallback content to display when no picture is set.
For the sl-icon we can use the same setup we have for the breadcrumbs; there we use an icon named `breadcrumb-separator`, that points to the `slash-forward` icon by default but for magister it's `chevron-right`

2024-06-12 14:20 UTC, jpzwarte commented on packages/components/avatar/src/avatar.scss
> +  border-radius: 50%;
Yep, discussed this with Roald: square isn't being used anywhere atm.

2024-06-13 07:06 UTC, jpzwarte commented on packages/components/avatar/src/avatar.spec.ts
> +    expect(el.renderRoot.querySelector('img')).not.to.exist;
Not really. That test explicitly tests whether the fallback content is rendered. I could test it there, but then it feels like i'm testing 2 things in 1 test.

2024-06-13 07:07 UTC, jpzwarte commented on packages/components/avatar/src/avatar.spec.ts
>    });
That's more a visual test i think. That's why we have Chromatic, right? ;)

2024-06-13 07:17 UTC, jpzwarte commented on packages/components/avatar/src/avatar.ts
>              <sl-tooltip id="avatar-tooltip">${this.displayName}</sl-tooltip>
Fixed

2024-06-14 06:23 UTC, merged