Fix/1480 padding border radius issues
sl-design-system/components pull request #1488
Opened 2024-08-29 08:07 UTC by Diaan

2024-08-29 15:01 UTC, Diaan commented
Made a PR so i could check chromatic, but Chromatic doesn't take new snapshots... 🤔

2024-09-03 06:05 UTC, anna-lach commented on packages/components/toggle-button/src/toggle-button.scss
>  :host {
Can you please add changeset? :)

2024-09-03 13:10 UTC, DanielleRameau requested changes
- [x] The buttons in the large toggle group shift/jump when one of them is selected
- [x] Tooltip margin and border-radius is different in toggle group compared with the regular tooltip
- [ ] The end button in text pressed variant has a odd white line on the right side (itslearning, magister, bingel DC)
- [x] Remove border ‘disabled pressed’, token should be the same as the background color (all themes except neon light and 

dark)

2024-09-04 14:43 UTC, Diaan commented
> The end button in text pressed variant has a odd white line on the right side (itslearning, magister, bingel DC)
Is nearly impossible to solve; this is a Safari issue that occurs when 4 properties are combined:

- `sl-toggle-group` needs to be places in a specific place in a grid
- overflow: hidden on the `sl-toggle-group`
- position:relative on the `sl-toggle-button`
- `border-radius` set to something other than 0.

Because of the first in this list the chance that this will occur in a CFA is pretty small, so we decided to not put more effort into this.

https://codepen.io/dianabroeders/pen/KKjrgao

2024-09-05 07:29 UTC, anna-lach approved these changes

2024-09-10 07:22 UTC, DanielleRameau approved these changes

2024-09-10 07:23 UTC, merged