Refactor packages
sl-design-system/components pull request #352
Opened 2023-04-17 14:33 UTC by jpzwarte

2023-04-24 10:25 UTC, anna-lach requested changes

2023-04-24 10:25 UTC, anna-lach commented on website/site.eleventy.cjs
Paths 
```
.addPassthroughCopy({ './../../packages/tokens/src/themes/sanoma-learning': `styles/slds-sanoma-learning` })
 .addPassthroughCopy({ './../../packages/tokens/src/themes/sanoma-learning/*.json': `_data` });
```

need to be changed to:
```
.addPassthroughCopy({ './../packages/themes/sanoma-learning': `styles/slds-sanoma-learning` })
 .addPassthroughCopy({ './../packages/tokens/src/sanoma-learning/*.json': `_data` });
```

2023-04-24 10:25 UTC, anna-lach commented on website/package.json
> +        "../packages/tokens:build",
The path needs to be changed to `"..:build:tokens",`

2023-04-24 10:26 UTC, anna-lach commented on website/src/site/styles/main.scss
These paths should be changed, as mentioned here: https://github.com/sanomalearning/design-system/pull/352#discussion_r1175074397 :)

2023-04-24 14:42 UTC, Diaan commented on tools/storybook-addon-themes/preset.js
this was used to give a (very minimal) default style to all the preview pages, such as the color, background color and font.
Without this the previews look a bit sad :(

2023-04-24 15:14 UTC, jpzwarte commented on packages/components/button/src/button.ts
> +  /** @private. */
It's not, but this way its not part of `custom-elements.json` :)

2023-04-24 15:22 UTC, jpzwarte commented on tsconfig.all.json
> +    { "path": "./packages/components/tooltip" }
Good point! We need some docs for that.

2023-04-24 15:27 UTC, jpzwarte commented on packages/tokens/src/themes/.DS_Store
I just deleted it *again*. It should never get added to git since it is in `.gitignore`...

2023-04-24 15:33 UTC, jpzwarte commented on tools/storybook-addon-themes/preset.js
Fixed

2023-04-25 06:08 UTC, anna-lach approved these changes

2023-04-26 09:20 UTC, jpzwarte commented on tsconfig.all.json
> +    { "path": "./packages/components/tooltip" }
Updated `CONTRIBUTING.md` with this info.

2023-04-28 07:26 UTC, merged