Feature/198 text field component
sl-design-system/components pull request #454
Opened 2023-05-22 09:33 UTC by anna-lach

Styled `sl-input` component
Styled `sl-label` component
Styled hint and validation

Contains changes after tokens grouping.

2023-05-22 10:45 UTC, jpzwarte approved these changes

2023-05-22 10:45 UTC, jpzwarte commented on packages/components/input/src/input.scss
> +@each $variant in $variants {
So in other stylesheets, I've moved this block of code to the top; between `:host {` and the actual component styling. So all the CSS variable stuff is grouped together.

2023-05-22 10:45 UTC, jpzwarte commented on packages/components/input/src/input.stories.ts
> +      ?readonly=${readonly}
Can you move this to the top with the other boolean properties?

2023-05-22 10:45 UTC, jpzwarte commented on packages/components/input/src/input.stories.ts
> +    </style><sl-input disabled value="I am disabled"></sl-input>`
Typo I assume :)

2023-05-22 10:45 UTC, jpzwarte commented on packages/components/input/src/input.ts
> +          @keydown=${this.#onKeydown}
Please sort the event handlers alphabetically

2023-05-22 10:45 UTC, jpzwarte commented on packages/components/input/src/input.ts
> +  #clicked = false;
Can you explain this bit?

2023-05-22 10:45 UTC, jpzwarte commented on packages/components/radio-group/src/radio-group.stories.ts
> +        <div slot="value-missing" error-size="sm">
Should the error size be configurable? It feels like too much?

2023-05-22 10:45 UTC, jpzwarte commented on packages/components/shared/src/controllers/validation.ts
> +  }
Please add newlines between rule blocks

2023-05-22 10:53 UTC, jpzwarte commented on packages/components/input/src/input.ts
> +  #clicked = false;
So affairs this goes against the browser heuristics. For example see the demo here: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

I really don't like going *against* browser behavior. 😕

2023-05-22 11:09 UTC, jpzwarte commented on packages/components/radio-group/src/radio-group.stories.ts
> +        <div slot="value-missing" error-size="sm">
Feels like the wrong approach for something that is pure styling. What about using a custom property?

```css
sl-input.mine {
  --sl-error-size: sm;
}
```

But you need container queries (style specifically) for that to work.

Perhaps
```
sl-input.mine {
  --sl-error-size: var(--sl-error-size-sm);
}
``` ?

2023-05-22 12:02 UTC, Diaan requested changes

2023-05-22 12:03 UTC, anna-lach commented on packages/components/input/src/input.scss
> +      sl-icon {
right :)

2023-05-22 12:05 UTC, anna-lach commented on packages/components/radio-group/src/radio-group.stories.ts
> +        <div slot="value-missing" error-size="sm">
We can use the default one, it was just an example :)

2023-05-22 12:27 UTC, anna-lach commented on packages/components/shared/src/controllers/validation.ts
> +    }
Prettier handled it :D

2023-05-23 06:38 UTC, anna-lach commented on packages/components/label/src/label.ts
> +      ${this.required ? html`<span class="required">(required)</span>` : ''}
good point, I need to add it here as well

2023-05-23 09:57 UTC, jpzwarte approved these changes

2023-05-23 11:56 UTC, Diaan approved these changes

2023-05-23 11:58 UTC, merged